// src/routes/(public)/donate/+page.svelte
<script lang="ts">
	import CardContent from '$lib/components/ui/card/card-content.svelte';
	import type { PageProps } from './$types';
	import { Card, CardHeader, CardTitle, CardDescription } from '$lib/components/ui/card';

	let { data }: PageProps = $props();

	import msfLogo from '../../../lib/assets/msflogo.svg';
	import { Button } from '$lib/components/ui/button';
</script>

<div class="flex h-full w-screen items-center justify-center">
	<Card class=" max-w-1/3">
		<CardHeader><CardTitle>Make a donation to Doctors without Borders</CardTitle></CardHeader>
		<CardContent class="flex flex-col gap-y-4">
			<img
				src={'https://www.doctorswithoutborders.org/themes/custom/msf/logo.svg'}
				class="relative! rounded-md bg-white p-2"
				alt="Doctors without Borders logo"
			/>
			<CardDescription
				>With all of the bad things in the world, I feel strongly about MSFs mission and capacity to
				do good. Please let me know if you make a donation!</CardDescription
			>
			<Button href="https://give.doctorswithoutborders.org/campaign/745298/donate?"
				>Donate now!</Button
			>
		</CardContent>
	</Card>
</div>

<svelte:head>
	<title>donate | henrik's wishlist</title>
</svelte:head>

// src/app/(public)/donate/page.tsx
import Image from "next/image";

import { LinkButton } from "~/components/ui/button-link";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";

export default function Page() {
  return (
    <div className="flex w-full justify-center px-4 pb-24 pt-4 md:px-0">
      <main className="flex max-w-md flex-col items-center gap-y-4">
        <h1 className="text-4xl font-bold">Donate to Charity</h1>
        <p className="text-base ">
          If you would like, instead of purchasing me a thing for Christmas, I
          would highly appreciate a donation to the charity below. <br /> Please
          let me know if you do this!
        </p>
        <MSFCard />
      </main>
    </div>
  );
}

export const dynamic = "force-static";

const MSFCard = () => (
  <Card className="w-full">
    <CardContent className="pt-6">
      <Image
        src={"https://www.doctorswithoutborders.org/themes/custom/msf/logo.svg"}
        className="!relative rounded-md"
        fill
        alt="MSF Logo"
      />
    </CardContent>
    <CardHeader>
      <CardTitle>Doctors Without Borders</CardTitle>
      <CardDescription>
        I remain a big fan of Doctors Without Borders. They&apos;re well known
        for the lifesaving work they do in wartorn and exploited regions around
        the world.
      </CardDescription>
    </CardHeader>
    <CardFooter>
      <LinkButton
        href="https://donate.doctorswithoutborders.org/secure/rr-donate-web"
        className="w-full"
        target="_blank"
      >
        Donate
      </LinkButton>
    </CardFooter>
  </Card>
);
